package com.lwm.springcloud.entities;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table msgindex
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Msgindex extends MsgindexKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgindex.receive
     *
     * @mbggenerated
     */
    private Boolean receive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgindex.unread
     *
     * @mbggenerated
     */
    private Boolean unread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgindex.receive
     *
     * @return the value of msgindex.receive
     *
     * @mbggenerated
     */
    public Boolean getReceive() {
        return receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgindex.receive
     *
     * @param receive the value for msgindex.receive
     *
     * @mbggenerated
     */
    public void setReceive(Boolean receive) {
        this.receive = receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgindex.unread
     *
     * @return the value of msgindex.unread
     *
     * @mbggenerated
     */
    public Boolean getUnread() {
        return unread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgindex.unread
     *
     * @param unread the value for msgindex.unread
     *
     * @mbggenerated
     */
    public void setUnread(Boolean unread) {
        this.unread = unread;
    }
}