package com.lwm.springcloud.entities;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table record
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Record extends RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.winner
     *
     * @mbggenerated
     */
    private String winner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.manual
     *
     * @mbggenerated
     */
    private String manual;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.winner
     *
     * @return the value of record.winner
     *
     * @mbggenerated
     */
    public String getWinner() {
        return winner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.winner
     *
     * @param winner the value for record.winner
     *
     * @mbggenerated
     */
    public void setWinner(String winner) {
        this.winner = winner == null ? null : winner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.manual
     *
     * @return the value of record.manual
     *
     * @mbggenerated
     */
    public String getManual() {
        return manual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.manual
     *
     * @param manual the value for record.manual
     *
     * @mbggenerated
     */
    public void setManual(String manual) {
        this.manual = manual == null ? null : manual.trim();
    }
}