package com.lwm.springcloud.entities;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table record
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.redsquare
     *
     * @mbggenerated
     */
    private Integer redsquare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.bluesquare
     *
     * @mbggenerated
     */
    private Integer bluesquare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.battletime
     *
     * @mbggenerated
     */
    private Date battletime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.redsquare
     *
     * @return the value of record.redsquare
     *
     * @mbggenerated
     */
    public Integer getRedsquare() {
        return redsquare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.redsquare
     *
     * @param redsquare the value for record.redsquare
     *
     * @mbggenerated
     */
    public void setRedsquare(Integer redsquare) {
        this.redsquare = redsquare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.bluesquare
     *
     * @return the value of record.bluesquare
     *
     * @mbggenerated
     */
    public Integer getBluesquare() {
        return bluesquare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.bluesquare
     *
     * @param bluesquare the value for record.bluesquare
     *
     * @mbggenerated
     */
    public void setBluesquare(Integer bluesquare) {
        this.bluesquare = bluesquare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.battletime
     *
     * @return the value of record.battletime
     *
     * @mbggenerated
     */
    public Date getBattletime() {
        return battletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.battletime
     *
     * @param battletime the value for record.battletime
     *
     * @mbggenerated
     */
    public void setBattletime(Date battletime) {
        this.battletime = battletime;
    }
}