package com.lwm.springcloud.entities;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table verification
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class VerificationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.sendID
     *
     * @mbggenerated
     */
    private Integer sendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.receiveID
     *
     * @mbggenerated
     */
    private Integer receiveid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.sendID
     *
     * @return the value of verification.sendID
     *
     * @mbggenerated
     */
    public Integer getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.sendID
     *
     * @param sendid the value for verification.sendID
     *
     * @mbggenerated
     */
    public void setSendid(Integer sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.receiveID
     *
     * @return the value of verification.receiveID
     *
     * @mbggenerated
     */
    public Integer getReceiveid() {
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.receiveID
     *
     * @param receiveid the value for verification.receiveID
     *
     * @mbggenerated
     */
    public void setReceiveid(Integer receiveid) {
        this.receiveid = receiveid;
    }
}