package com.lwm.springcloud.dao;

import com.lwm.springcloud.entities.*;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgindexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int countByExample(MsgindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int deleteByExample(MsgindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MsgindexKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int insert(Msgindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int insertSelective(Msgindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    List<Msgindex> selectByExample(MsgindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    Msgindex selectByPrimaryKey(MsgindexKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Msgindex record, @Param("example") MsgindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Msgindex record, @Param("example") MsgindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Msgindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgindex
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Msgindex record);
}